# config.yaml
server:
  image:
    repository: hashicorp/vault-enterprise
    tag: 1.13.1-ent
  enterpriseLicense:
    secretName: vault-ent-license
  dev:
    enabled: true
    devRootToken: "root"

ui:
  # True if you want to create a Service entry for the Vault UI.
  #
  # serviceType can be used to control the type of service created. For
  # example, setting this to "LoadBalancer" will create an external load
  # balancer (for supported K8S installations) to access the UI.
  enabled: true

